### ISSUE TITLE
invalid memory address or nil pointer dereference - FirstOrInit / FirstOrCreate

### ISSUE THREAD

**Issue by drnic** [go-gorm/gorm#116]
``` go
func main() {
    db, err := gorm.Open("postgres", "user=drnic dbname=gorm_test sslmode=disable")
... other setup from README

    db.AutoMigrate(User{})

    user := User{}
    db.FirstOrInit(&user, User{Name: "non_existing"})
    fmt.Printf("%#v\n", user)
}
```

is raising a panic - (also for `FirstOrCreate`)

```
go run main.go

(/private/tmp/golang-orm-tests/gorm/main.go:67) 
[2014-05-15 11:36:25]  pq: syntax error at or near "user" 

(/private/tmp/golang-orm-tests/gorm/main.go:67) 
[2014-05-15 11:36:25]  [1.31ms]  CREATE TABLE user ("id" bigserial PRIMARY KEY,"birthday" timestamp with time zone,"age" bigint,"name" varchar(255)  ,"created_at" timestamp with time zone,"updated_at" timestamp with time zone,"deleted_at" timestamp with time zone,"billing_address_id" bigint,"shipping_address_id" bigint)

(/private/tmp/golang-orm-tests/gorm/main.go:70) 
[2014-05-15 11:36:25]  pq: syntax error at or near "." 

(/private/tmp/golang-orm-tests/gorm/main.go:70) 
[2014-05-15 11:36:25]  [1.18ms]  SELECT * FROM user  WHERE (deleted_at IS NULL OR deleted_at <= '0001-01-02') AND (("name" = 'non_existing')) ORDER BY user.id LIMIT 1
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x63a89]

goroutine 1 [running]:
runtime.panic(0x21c500, 0x4ccab9)
    /usr/local/go/src/pkg/runtime/panic.c:266 +0xb6
github.com/jinzhu/gorm.(*DB).FirstOrInit(0xc210010320, 0x1b1c80, 0xc2100b58c0, 0xc2100b4440, 0x1, ...)
    /Users/drnic/Projects/golang/src/github.com/jinzhu/gorm/main.go:170 +0x2f9
main.main()
    /private/tmp/golang-orm-tests/gorm/main.go:70 +0x3ad

goroutine 3 [chan receive]:
database/sql.(*DB).connectionOpener(0xc210070500)
    /usr/local/go/src/pkg/database/sql/sql.go:574 +0x3e
created by database/sql.Open
    /usr/local/go/src/pkg/database/sql/sql.go:436 +0x24d

goroutine 4 [syscall]:
runtime.goexit()
    /usr/local/go/src/pkg/runtime/proc.c:1394
exit status 2
```

Am I creating the `user` incorrectly? Ideas?

**Comment by bobobo1618** [comment]
Possibly related, possibly not, I'm seeing the same thing:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0xcb39f]

goroutine 16 [running]:
runtime.panic(0x33b720, 0x552024)
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/panic.c:279 +0xf5
github.com/jinzhu/gorm.(*DB).First(0xc2082418c0, 0x307cc0, 0xc2080cdb30, 0x0, 0x0, 0x0, 0x0)
	/Users/lucas/.Go/src/github.com/jinzhu/gorm/main.go:182 +0x1bf
github.com/jinzhu/gorm.(*DB).FirstOrCreate(0xc208241810, 0x307cc0, 0xc2080cdb30, 0x0, 0x0, 0x0, 0xc208241810)
	/Users/lucas/.Go/src/github.com/jinzhu/gorm/main.go:227 +0x8b
main.(*FaceThread).ToOrm(0xc208018550, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/lucas/.Go/src/facething/face_data.go:75 +0x11f
main.main()
	/Users/lucas/.Go/src/facething/main.go:37 +0x519

goroutine 19 [finalizer wait]:
runtime.park(0x19100, 0x555ba8, 0x554649)
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x555ba8, 0x554649)
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/proc.c:1445

goroutine 20 [chan receive]:
database/sql.(*DB).connectionOpener(0xc208058900)
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/database/sql/sql.go:583 +0x48
created by database/sql.Open
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/database/sql/sql.go:442 +0x27c

goroutine 17 [syscall]:
runtime.goexit()
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/proc.c:1445

goroutine 26 [select]:
net/http.(*persistConn).readLoop(0xc2080500b0)
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/net/http/transport.go:868 +0x829
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/net/http/transport.go:600 +0x93f

goroutine 27 [select]:
net/http.(*persistConn).writeLoop(0xc2080500b0)
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/net/http/transport.go:885 +0x38f
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/net/http/transport.go:601 +0x957

goroutine 31 [select]:
net/http.(*persistConn).readLoop(0xc208241080)
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/net/http/transport.go:868 +0x829
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/net/http/transport.go:600 +0x93f

goroutine 33 [select]:
net/http.(*persistConn).writeLoop(0xc208241080)
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/net/http/transport.go:885 +0x38f
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/net/http/transport.go:601 +0x957
```

The relevant code looks approximately like this:

```go
func (t *FaceThread) ToOrm() Thread {
	thread := new(Thread)
	db.Where(Thread{
		NetworkId: t.Id,
		Network:   Network{Name: "Facebook"},
	}).FirstOrCreate(thread)
}
```

Any clue what's going on?

**Comment by bobobo1618** [comment]
Don't worry, I suck at pointers. Sorry for the trouble.
