### ISSUE TITLE
FirstOrInit or FirstOrCreate doesn't work with sqlite3

### ISSUE THREAD

**Issue by nemith** [go-gorm/gorm#146]
I have the following simple example

```
package main

import (
    "fmt"
    "github.com/jinzhu/gorm"
    _ "github.com/mattn/go-sqlite3"
)

type User struct {
    Name string
}

func main() {
    db, err := gorm.Open("sqlite3", "/tmp/test.db")
    if err != nil {
        panic(err)
    }

    db.AutoMigrate(&User{})

    user := User{}
    db.Where(User{Name: "nemith"}).FirstOrInit(&user)
    //  db.FirstOrInit(&user, User{Name: "nemith"})
    fmt.Printf("%#v\n", user)
}
```

If i use `db.Where(User{Name: "nemith"}).FirstOrInit(&user)` I get the following output.

```
bbennett@strongbad:~$ go run test.go
main.User{Name:""}
```

This happens even if there is an existing record.

If i use `db.FirstOrInit(&user, User{Name: "nemith"})` I get a traceback

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x40fe1f2]

goroutine 16 [running]:
runtime.panic(0x4214960, 0x4305044)
    /usr/local/Cellar/go/1.3/libexec/src/pkg/runtime/panic.c:279 +0xf5
github.com/jinzhu/gorm.(*DB).FirstOrInit(0xc2080481e0, 0x41c74c0, 0xc208000590, 0xc2080005a0, 0x1, 0x1, 0x0)
    /Users/bbennett/Devel/go/src/github.com/jinzhu/gorm/main.go:171 +0x312
main.main()
    /Users/bbennett/test.go:23 +0x254

goroutine 17 [runnable]:
runtime.MHeap_Scavenger()
    /usr/local/Cellar/go/1.3/libexec/src/pkg/runtime/mheap.c:507
runtime.goexit()
    /usr/local/Cellar/go/1.3/libexec/src/pkg/runtime/proc.c:1445

goroutine 18 [runnable]:
bgsweep()
    /usr/local/Cellar/go/1.3/libexec/src/pkg/runtime/mgc0.c:1976
runtime.goexit()
    /usr/local/Cellar/go/1.3/libexec/src/pkg/runtime/proc.c:1445

goroutine 19 [runnable]:
runfinq()
    /usr/local/Cellar/go/1.3/libexec/src/pkg/runtime/mgc0.c:2606
runtime.goexit()
    /usr/local/Cellar/go/1.3/libexec/src/pkg/runtime/proc.c:1445

goroutine 20 [runnable]:
database/sql.(*DB).connectionOpener(0xc20804d500)
    /usr/local/Cellar/go/1.3/libexec/src/pkg/database/sql/sql.go:582
created by database/sql.Open
    /usr/local/Cellar/go/1.3/libexec/src/pkg/database/sql/sql.go:442 +0x27c

goroutine 21 [runnable]:
github.com/jinzhu/gorm.(*safeMap).Set(0xc2080002a0, 0x4233310, 0x4, 0xc208000e80, 0x4)
    /Users/bbennett/Devel/go/src/github.com/jinzhu/gorm/utils.go:21
created by github.com/jinzhu/gorm.toSnake
    /Users/bbennett/Devel/go/src/github.com/jinzhu/gorm/utils.go:54 +0x270

goroutine 17 [syscall]:
runtime.goexit()
    /usr/local/Cellar/go/1.3/libexec/src/pkg/runtime/proc.c:1445

goroutine 22 [runnable]:
github.com/jinzhu/gorm.(*safeMap).Set(0xc2080002a0, 0x4231a90, 0x4, 0xc208000300, 0x4)
    /Users/bbennett/Devel/go/src/github.com/jinzhu/gorm/utils.go:21
created by github.com/jinzhu/gorm.toSnake
    /Users/bbennett/Devel/go/src/github.com/jinzhu/gorm/utils.go:54 +0x270

goroutine 23 [runnable]:
github.com/jinzhu/gorm.(*safeMap).Set(0xc2080002a0, 0x4233310, 0x4, 0xc208000358, 0x4)
    /Users/bbennett/Devel/go/src/github.com/jinzhu/gorm/utils.go:21
created by github.com/jinzhu/gorm.toSnake
    /Users/bbennett/Devel/go/src/github.com/jinzhu/gorm/utils.go:54 +0x270

goroutine 24 [runnable]:
github.com/jinzhu/gorm.(*safeMap).Set(0xc2080002a0, 0x4233310, 0x4, 0xc2080005d0, 0x4)
    /Users/bbennett/Devel/go/src/github.com/jinzhu/gorm/utils.go:21
created by github.com/jinzhu/gorm.toSnake
    /Users/bbennett/Devel/go/src/github.com/jinzhu/gorm/utils.go:54 +0x270

goroutine 25 [runnable]:
github.com/jinzhu/gorm.(*safeMap).Set(0xc2080002a0, 0x4233310, 0x4, 0xc208000858, 0x4)
    /Users/bbennett/Devel/go/src/github.com/jinzhu/gorm/utils.go:21
created by github.com/jinzhu/gorm.toSnake
    /Users/bbennett/Devel/go/src/github.com/jinzhu/gorm/utils.go:54 +0x270

goroutine 26 [runnable]:
github.com/jinzhu/gorm.(*safeMap).Set(0xc2080002b0, 0x4235a70, 0x2, 0xc208000a22, 0x2)
    /Users/bbennett/Devel/go/src/github.com/jinzhu/gorm/utils.go:21
created by github.com/jinzhu/gorm.snakeToUpperCamel
    /Users/bbennett/Devel/go/src/github.com/jinzhu/gorm/utils.go:72 +0x353

goroutine 27 [runnable]:
github.com/jinzhu/gorm.(*safeMap).Set(0xc2080002a0, 0x4231a90, 0x4, 0xc208000a40, 0x4)
    /Users/bbennett/Devel/go/src/github.com/jinzhu/gorm/utils.go:21
created by github.com/jinzhu/gorm.toSnake
    /Users/bbennett/Devel/go/src/github.com/jinzhu/gorm/utils.go:54 +0x270

goroutine 28 [runnable]:
github.com/jinzhu/gorm.(*DB).print(0xc208048960, 0xc20803f2a0, 0x2, 0x2)
    /Users/bbennett/Devel/go/src/github.com/jinzhu/gorm/main_private.go:43
created by github.com/jinzhu/gorm.(*DB).err
    /Users/bbennett/Devel/go/src/github.com/jinzhu/gorm/main_private.go:30 +0x1be
exit status 2
```

**Comment by maran** [comment]
I can confirm this is still the case. Using @nemith's work around works fine though.

**Comment by andreychernih** [comment]
+1 still an issue with `db.FirstOrInit(&user, User{Name: "nemith"})` version. Workaround works though.

**Comment by Knorkebrot** [comment]
Not an sqlite problem, this is reproducible with postgres as well.
