### ISSUE TITLE
Gorm on sql Azure

### ISSUE THREAD

**Issue by Archie1978** [go-gorm/gorm#2495]
I try to use gorm on AZURE Serveur SQL and I have several problem.
My program is simple:
```

type Pays struct {
	Id		int64	`gorm:"primary_key"`
	Nom 		string
}

	connString := fmt.Sprintf("server=%s;user id=%s;password=%s;port=%d;database=%s;",
		server, user, password, port, database)
	GORMdb, err := gorm.Open("mssql", connString)
	if err != nil {
		panic("failed to connect database")
	}

	// Then you could invoke `*sql.DB`'s functions with it
	GORMdb.DB().Ping()
	GORMdb.DB().SetMaxIdleConns(10)
	GORMdb.DB().SetMaxOpenConns(100)

	// Disable table name's pluralization
	GORMdb.SingularTable(true)

	// Create table
	GORMdb.AutoMigrate(&Pays{})

	// Mise a jour des pays
	GORMdb.Save(Pays{Id:1,Nom:"France"})

```

AutoMigrate create a table, but when I save, I have a big crack.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb0 pc=0x548266]

goroutine 1 [running]:
github.com/jinzhu/gorm.(*DB).clone(0x0, 0xc0003b60c0)
	/home/ron/workspace/go/src/github.com/jinzhu/gorm/main.go:777 +0x26
github.com/jinzhu/gorm.(*DB).NewScope(0x0, 0x726dc0, 0xc0003b60c0, 0xc00036fd60)
	/home/ron/workspace/go/src/github.com/jinzhu/gorm/main.go:181 +0x2f
github.com/jinzhu/gorm.(*DB).Save(0x0, 0x726dc0, 0xc0003b60c0, 0x1)
	/home/ron/workspace/go/src/github.com/jinzhu/gorm/main.go:445 +0x43

I have upgrade my gorm lib this morning. Someone has already tried to use sql azure with gorm ?

**Comment by Archie1978** [comment]
I saw my error, I forgot to initilize the connector gorm.DB and the shots he remained at null XD. But do you have gorm examples with SQL AZURE?
