### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by klivitam-Jiang** [go-gorm/gorm#2574]
```
type Artical struct {
	Id            int    `json:"id" gorm:"column:id:primary_key"`
	Title         string `json:"title" gorm:"column:title"`    
	Content       string `json:"content"  gorm:"column:content"`   
	CollectId     int `json:"collect_id"  gorm:"column:collect_id"`  
}

func (m *Models) GetAllArticals(id int) (isSucc bool, articals []Artical) {
	err := db.DefaultDB.
		Table("articals").
		Find(&articals). // error line...
		Error

	fmt.Println(err.Error())
	if err != nil {
		return false, nil
	}
	return
}
```

 Handler crashed with error runtime error: invalid memory address or nil pointer dereference

i just test find result with mysql,but show runtime error

**Comment by kagile** [comment]
Same issue.

**Comment by kagile** [comment]
Trace:
```

goroutine 67 [running]:
github.com/jinzhu/gorm.(*Scope).callCallbacks.func1(0xc000274100)
        /home/krupal/go/go1.12.5/pkg/mod/github.com/jinzhu/gorm@v1.9.10/scope.go:884 +0xb0
panic(0xc16360, 0x148dff0)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
database/sql.(*DB).conn(0x0, 0xec2120, 0xc0000ba010, 0x101, 0xd00ed6, 0x3, 0xffffffffffffffff)
        /usr/local/go/src/database/sql/sql.go:1080 +0x3a
database/sql.(*DB).query(0x0, 0xec2120, 0xc0000ba010, 0xc0000442c0, 0x158, 0xc000399180, 0x2, 0x2, 0x1, 0x39a2f4bd676e0333, ...)
        /usr/local/go/src/database/sql/sql.go:1513 +0x66
database/sql.(*DB).QueryContext(0x0, 0xec2120, 0xc0000ba010, 0xc0000442c0, 0x158, 0xc000399180, 0x2, 0x2, 0x0, 0xbc2c80, ...)
        /usr/local/go/src/database/sql/sql.go:1495 +0xd1
database/sql.(*DB).Query(0x0, 0xc0000442c0, 0x158, 0xc000399180, 0x2, 0x2, 0x203000, 0x7f211d04d960, 0x0)
        /usr/local/go/src/database/sql/sql.go:1509 +0x83
github.com/jinzhu/gorm.queryCallback(0xc000274100)
        /home/krupal/go/go1.12.5/pkg/mod/github.com/jinzhu/gorm@v1.9.10/callback_query.go:67 +0x3b2
github.com/jinzhu/gorm.(*Scope).callCallbacks(0xc000274100, 0xc000276ec0, 0x3, 0x4, 0x0)
        /home/krupal/go/go1.12.5/pkg/mod/github.com/jinzhu/gorm@v1.9.10/scope.go:888 +0x88
github.com/jinzhu/gorm.(*DB).Take(0xc000153ee0, 0xb9b7a0, 0xc000398e40, 0x0, 0x0, 0x0, 0xc000153ee0)
        /home/krupal/go/go1.12.5/pkg/mod/github.com/jinzhu/gorm@v1.9.10/main.go:338 +0xc6
github.com/x/api/v1/scanner/rpc.getSubscriptionRequestsFromDb(0xc00038c000, 0xc000454328, 0x2, 0x1, 0xc0000c03c0, 0xc0003299d8)
        /home/krupal/GoWorkspace/proj/github.com/x/api/v1/scanner/rpc/controller.go:250 +0x525
github.com/x/api/v1/scanner/rpc.(*server).Scan(0xc00000f120, 0xc00045a1e0, 0xec7660, 0xc0004731d0, 0xc00000f120, 0xd0)
        /home/krupal/GoWorkspace/proj/github.com/x/api/v1/scanner/rpc/service.go:114 +0xfd5
github.com//api/v1/scanner/rpc._ScanRpc_Scan_Handler(0xc41ca0, 0xc00000f120, 0xec64c0, 0xc00049c000, 0xc0003b9ca8, 0x1)
        /home/krupal/GoWorkspace/proj/github.com/x/api/v1/scanner/rpc/scan_rpc.pb.go:1092 +0x109
github.com/x/api/v1/auth.StreamInterceptor(0xc41ca0, 0xc00000f120, 0xec64c0, 0xc00049c000, 0xc00048c140, 0xd33ba0, 0xec21a0, 0xc000450270)
        /home/krupal/GoWorkspace/proj/github.com/x/api/v1/auth/interceptor.go:103 +0x246
google.golang.org/grpc.(*Server).processStreamingRPC(0xc0003b6420, 0xeca3c0, 0xc000306600, 0xc00048e000, 0xc000382660, 0x1494d80, 0x0, 0x0, 0x0)
        /home/krupal/go/go1.12.5/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:1206 +0x462
google.golang.org/grpc.(*Server).handleStream(0xc0003b6420, 0xeca3c0, 0xc000306600, 0xc00048e000, 0x0)
        /home/krupal/go/go1.12.5/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:1279 +0xd3f
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0002d71c0, 0xc0003b6420, 0xeca3c0, 0xc000306600, 0xc00048e000)
        /home/krupal/go/go1.12.5/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:710 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/krupal/go/go1.12.5/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:708 +0xa1

```

**Comment by wumoxi** [comment]
```go
type Artical struct {
	Id            int    `json:"id" gorm:"column:id:primary_key"`
	Title         string `json:"title" gorm:"column:title"`    
	Content       string `json:"content"  gorm:"column:content"`   
	CollectId     int `json:"collect_id"  gorm:"column:collect_id"`  
}

func (m *Models) GetAllArticals(id int) (isSucc bool, articals []*Artical) {
	err := db.DefaultDB.
		Table("articals").
		Find(&articals). // error line...
		Error

	fmt.Println(err.Error())
	if err != nil {
		return false, nil
	}
	return
}
```

given a pointer

**Comment by kagile** [comment]
@wumoxi 
In my case:


```
func someFunc(db *gorm.DB, userId string) (*schema.SubscriptionRequests, error){
	var r Xyz
	find := db.Table("tbl").
		Where("userid = ? and active = ?", userId, true).
		Take(&r)

	if find.Error != nil {
		log.Error(find.Error)
		return nil, find.Error
	}
	return &r, nil
}
```

Where is the nil pointer?

**Comment by wumoxi** [comment]
@kagile You can do this
```go
func someFunc(db *gorm.DB, userId string) (r *Xyz, err error){
	err = db.Table("tbl").
		Where("userid = ? and active = ?", userId, true).
		Take(&r).Error

	if find.Error != nil {
		log.Error(find.Error)
		return
	}
	return
}
```

**Comment by kagile** [comment]
@wumoxi @klivitam-Jiang 
Oh, I solved it by adding dialect to importt:

`    _ "github.com/jinzhu/gorm/dialects/postgres"`

@jinzhu The error is very confusing.
