### ISSUE TITLE
Panic when tertiary embedded field pointer + gorm tag  [gorm.io/gorm v0.2.12]

### ISSUE THREAD

**Issue by ItsLeeOwen** [go-gorm/gorm#3071]
The following struct composition panics when using a pointer for `ReadOnly *bool` with tag `gorm:"default:false"`  on the underlying document model.

```
cd tests
go test -v -run TestEmbeddedStruct

testing postgres...
=== RUN   TestEmbeddedStruct
--- FAIL: TestEmbeddedStruct (0.08s)
panic: reflect: call of reflect.Value.IsNil on zero Value [recovered]
	panic: reflect: call of reflect.Value.IsNil on zero Value

goroutine 20 [running]:
testing.tRunner.func1.1(0x4722b80, 0xc000496640)
	/usr/local/Cellar/go/1.14.3/libexec/src/testing/testing.go:940 +0x2f5
testing.tRunner.func1(0xc0000c9560)
	/usr/local/Cellar/go/1.14.3/libexec/src/testing/testing.go:943 +0x3f9
panic(0x4722b80, 0xc000496640)
	/usr/local/Cellar/go/1.14.3/libexec/src/runtime/panic.go:969 +0x166
reflect.Value.IsNil(...)
	/usr/local/Cellar/go/1.14.3/libexec/src/reflect/value.go:1063
gorm.io/gorm/schema.(*Field).setupValuerAndSetter.func8(0x4765c20, 0xc0000e5490, 0x199, 0x46f90a0, 0x4d37ac0, 0xc0000fb380, 0xc0000dee01, 0xc0000a9500)
	/gorm/schema/field.go:439 +0xd74
gorm.io/gorm/schema.(*Field).setupValuerAndSetter.func18(0x4765c20, 0xc0000e5490, 0x199, 0x46f90a0, 0x4d37ac0, 0x1, 0xa0)
	/gorm/schema/field.go:750 +0x67
gorm.io/gorm/callbacks.ConvertToCreateValues(0xc000495680, 0xc00048a700, 0x7, 0x8, 0xc000496620, 0x1, 0x1)
	/gorm/callbacks/create.go:285 +0x201c
gorm.io/gorm/callbacks.CreateWithReturning(0xc0004925a0)
	/gorm/callbacks/create.go:117 +0xc2a
gorm.io/gorm.(*processor).Execute(0xc000204d40, 0xc0004925a0)
	/gorm/callbacks.go:100 +0x21d
gorm.io/gorm.(*DB).Save(0xc000202e10, 0x46e69a0, 0xc0000e5490, 0x47c8b06)
	/gorm/finisher_api.go:36 +0x53b
gorm.io/gorm/tests_test.TestEmbeddedStruct(0xc0000c9560)
	/gorm/tests/embedded_struct_test.go:67 +0x61a
testing.tRunner(0xc0000c9560, 0x47f78b0)
	/usr/local/Cellar/go/1.14.3/libexec/src/testing/testing.go:991 +0xdc
created by testing.(*T).Run
	/usr/local/Cellar/go/1.14.3/libexec/src/testing/testing.go:1042 +0x357
exit status 2
FAIL	gorm.io/gorm/tests	0.511s
```

### What version of Go are you using (`go version`)?
1.14.3

### Which database and its version are you using?
postgres 12.3

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**
```go
package tests_test

import (
	"database/sql/driver"
	"encoding/json"
	"errors"
	"testing"

	"gorm.io/gorm"
)

func TestEmbeddedStruct(t *testing.T) {
	type Doc struct {
		Id       int64
		ReadOnly *bool `gorm:"default:false"`
	}

	type BasePost struct {
		Doc
		Title string
		URL   string
	}

	type Author struct {
		ID    string
		Name  string
		Email string
	}

	type HNPost struct {
		BasePost
		Author  `gorm:"EmbeddedPrefix:user_"` // Embedded struct
		Upvotes int32
	}

	type EngadgetPost struct {
		BasePost BasePost `gorm:"Embedded"`
		Author   Author   `gorm:"Embedded;EmbeddedPrefix:author_"` // Embedded struct
		ImageUrl string
	}

	DB.Migrator().DropTable(&HNPost{}, &EngadgetPost{})
	if err := DB.Migrator().AutoMigrate(&HNPost{}, &EngadgetPost{}); err != nil {
		t.Fatalf("failed to auto migrate, got error: %v", err)
	}

	for _, name := range []string{"author_id", "author_name", "author_email"} {
		if !DB.Migrator().HasColumn(&EngadgetPost{}, name) {
			t.Errorf("should has prefixed column %v", name)
		}
	}

	stmt := gorm.Statement{DB: DB}
	if err := stmt.Parse(&EngadgetPost{}); err != nil {
		t.Fatalf("failed to parse embedded struct")
	} else if len(stmt.Schema.PrimaryFields) != 1 {
		t.Errorf("should have only one primary field with embedded struct, but got %v", len(stmt.Schema.PrimaryFields))
	}

	for _, name := range []string{"user_id", "user_name", "user_email"} {
		if !DB.Migrator().HasColumn(&HNPost{}, name) {
			t.Errorf("should has prefixed column %v", name)
		}
	}

	// save embedded struct
	DB.Save(&HNPost{BasePost: BasePost{Title: "news"}})
	DB.Save(&HNPost{BasePost: BasePost{Title: "hn_news"}})
	var news HNPost
	if err := DB.First(&news, "title = ?", "hn_news").Error; err != nil {
		t.Errorf("no error should happen when query with embedded struct, but got %v", err)
	} else if news.Title != "hn_news" {
		t.Errorf("embedded struct's value should be scanned correctly")
	}

	DB.Save(&EngadgetPost{BasePost: BasePost{Title: "engadget_news"}})
	var egNews EngadgetPost
	if err := DB.First(&egNews, "title = ?", "engadget_news").Error; err != nil {
		t.Errorf("no error should happen when query with embedded struct, but got %v", err)
	} else if egNews.BasePost.Title != "engadget_news" {
		t.Errorf("embedded struct's value should be scanned correctly")
	}
}

func TestEmbeddedPointerTypeStruct(t *testing.T) {
	type BasePost struct {
		Id    int64
		Title string
		URL   string
	}

	type HNPost struct {
		*BasePost
		Upvotes int32
	}

	DB.Migrator().DropTable(&HNPost{})
	if err := DB.Migrator().AutoMigrate(&HNPost{}); err != nil {
		t.Fatalf("failed to auto migrate, got error: %v", err)
	}

	DB.Create(&HNPost{BasePost: &BasePost{Title: "embedded_pointer_type"}})

	var hnPost HNPost
	if err := DB.First(&hnPost, "title = ?", "embedded_pointer_type").Error; err != nil {
		t.Errorf("No error should happen when find embedded pointer type, but got %v", err)
	}

	if hnPost.Title != "embedded_pointer_type" {
		t.Errorf("Should find correct value for embedded pointer type")
	}
}

type Content struct {
	Content interface{} `gorm:"type:String"`
}

func (c Content) Value() (driver.Value, error) {
	return json.Marshal(c)
}

func (c *Content) Scan(src interface{}) error {
	b, ok := src.([]byte)
	if !ok {
		return errors.New("Embedded.Scan byte assertion failed")
	}

	var value Content
	if err := json.Unmarshal(b, &value); err != nil {
		return err
	}

	*c = value

	return nil
}

func TestEmbeddedScanValuer(t *testing.T) {
	type HNPost struct {
		gorm.Model
		Content
	}

	DB.Migrator().DropTable(&HNPost{})
	if err := DB.Migrator().AutoMigrate(&HNPost{}); err != nil {
		t.Fatalf("failed to auto migrate, got error: %v", err)
	}

	hnPost := HNPost{Content: Content{Content: "hello world"}}

	if err := DB.Create(&hnPost).Error; err != nil {
		t.Errorf("Failed to create got error %v", err)
	}
}
```

**Comment by jinzhu** [comment]
Fixed this, please upgrade to v0.2.13
