### ISSUE TITLE
Many2Many Association operations panic with PostgreSQL UUID primary key

### ISSUE THREAD

**Issue by dre1080** [go-gorm/gorm#3182]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/45

## Description

When creating or appending associations with PostgreSQL UUID primary keys.
I also tried using a `string` Go type for the UUID primary key Go type.

it always panics with the following error:

```sh
[2.360ms] [rows:2] INSERT INTO "categories" ("title") VALUES ('Coding'),('Golang') ON CONFLICT DO NOTHING RETURNING "id"
--- FAIL: TestGORM (0.02s)
panic: reflect: slice index out of range [recovered]
        panic: reflect: slice index out of range

goroutine 18 [running]:
testing.tRunner.func1.1(0xd0ed00, 0xeb9780)
        /usr/lib/go-1.14/src/testing/testing.go:940 +0x421
testing.tRunner.func1(0xc0000a0360)
        /usr/lib/go-1.14/src/testing/testing.go:943 +0x600
panic(0xd0ed00, 0xeb9780)
        /usr/lib/go-1.14/src/runtime/panic.go:975 +0x3e3
reflect.Value.Index(0xc000213e40, 0xc0002301c0, 0x97, 0x2, 0xc0007000a0, 0x191, 0x196)
        /usr/lib/go-1.14/src/reflect/value.go:939 +0x565
gorm.io/gorm/callbacks.CreateWithReturning(0xc0004dc0f0)
        ~/playground/gorm/callbacks/create.go:153 +0xa08
gorm.io/gorm.(*processor).Execute(0xc000021e00, 0xc0004dc0f0)
        ~/playground/gorm/callbacks.go:100 +0x1a0
gorm.io/gorm.(*DB).Create(0xc0004dc0f0, 0xc000213e40, 0xc0002301c0, 0x1)
        ~/playground/gorm/finisher_api.go:18 +0x13a
gorm.io/gorm/callbacks.SaveAfterAssociations(0xc0006ce990)
        ~/playground/gorm/callbacks/associations.go:295 +0x2b65
gorm.io/gorm.(*processor).Execute(0xc000021e00, 0xc0006ce990)
        ~/playground/gorm/callbacks.go:100 +0x1a0
gorm.io/gorm.(*DB).Create(0xc00020a240, 0xcfbe40, 0xc000213c00, 0x1368c45)
        ~/playground/gorm/finisher_api.go:18 +0x13a
gorm.io/playground.TestGORM(0xc0000a0360)
        ~/playground/main_test.go:34 +0x2d4
testing.tRunner(0xc0000a0360, 0xde8478)
        /usr/lib/go-1.14/src/testing/testing.go:991 +0x1ec
created by testing.(*T).Run
        /usr/lib/go-1.14/src/testing/testing.go:1042 +0x661
FAIL    gorm.io/playground      2.235s
FAIL
```

**Comment by jinzhu** [comment]
Fixed, thank you for your report.

**Comment by youncccat** [comment]
@dre1080 Thx for your PR that resolving this problem, but there has another bug that the program will stick to when calling `Association Append` multiple times.
