### ISSUE TITLE
Nullable foreign keys with null value result into db.Find panicking 

### ISSUE THREAD

**Issue by L1ghtman2k** [go-gorm/gorm#3212]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/52

## Description

When I have 2 structs as follows:

```
type HostGroup struct {
	ID uuid.UUID `json:"id,omitempty" gorm:"type:uuid;primary_key;"`

	Hosts []*Host `json:"omitempty" gorm:"foreignkey:HostGroupID; constraint:OnUpdate:RESTRICT,OnDelete:RESTRICT"`
}

type Host struct {
	ID uuid.UUID `json:"id,omitempty" gorm:"type:uuid;primary_key;"`

	// The ID of a host group that the host belongs to.
	HostGroupID *uuid.UUID `json:"host_group_id,omitempty" gorm:"type:uuid"`
}
```
where Host belongs to a HostGroup,

if I create a sample Host object with null foreign key `DB.Exec("INSERT INTO hosts (id) VALUES ('22222222-2222-2222-2222-222222222222')")`, and then try to fetch all of the entries using `DB.Find(&hosts)` gorm panics with a following stacktrace:

```
--- FAIL: TestGORM (0.01s)
panic: value method github.com/gofrs/uuid.UUID.Value called using nil *UUID pointer [recovered]
	panic: value method github.com/gofrs/uuid.UUID.Value called using nil *UUID pointer

goroutine 6 [running]:
testing.tRunner.func1.1(0xd3d960, 0xc000030e90)
	/opt/hostedtoolcache/go/1.14.6/x64/src/testing/testing.go:988 +0x452
testing.tRunner.func1(0xc000556120)
	/opt/hostedtoolcache/go/1.14.6/x64/src/testing/testing.go:991 +0x600
panic(0xd3d960, 0xc000030e90)
	/opt/hostedtoolcache/go/1.14.6/x64/src/runtime/panic.go:975 +0x3e3
github.com/gofrs/uuid.(*UUID).Value(0x0, 0xdaa5e0, 0x0, 0x7f1fa35059b0, 0x0)
	<autogenerated>:1 +0xd0
gorm.io/gorm/schema.(*Field).setupValuerAndSetter.func17(0xd60da0, 0xc0001411e0, 0x199, 0xdaa5e0, 0x0, 0x0, 0xc000194420)
	/home/runner/work/playground/playground/gorm/schema/field.go:749 +0xae
gorm.io/gorm/schema.(*Field).setupValuerAndSetter.func17(0xd60da0, 0xc0001411e0, 0x199, 0xc0000a6040, 0xc0000102d0, 0x0, 0x0)
	/home/runner/work/playground/playground/gorm/schema/field.go:760 +0x3a9
gorm.io/gorm.Scan(0xc000542a00, 0xc0005453e0, 0xc00009e000)
	/home/runner/work/playground/playground/gorm/scan.go:148 +0xcb7
gorm.io/gorm/callbacks.Query(0xc0005453e0)
	/home/runner/work/playground/playground/gorm/callbacks/query.go:34 +0x534
gorm.io/gorm.(*processor).Execute(0xc0000a7dc0, 0xc0005453e0)
	/home/runner/work/playground/playground/gorm/callbacks.go:100 +0x1a0
gorm.io/gorm.(*DB).Find(0xc0001ac240, 0xcfafa0, 0xc0001410c0, 0x0, 0x0, 0x0, 0xc000545350)
	/home/runner/work/playground/playground/gorm/finisher_api.go:107 +0x165
gorm.io/playground.TestGORM(0xc000556120)
	/home/runner/work/playground/playground/main_test.go:32 +0x2dc
testing.tRunner(0xc000556120, 0xdee518)
	/opt/hostedtoolcache/go/1.14.6/x64/src/testing/testing.go:1039 +0x1ec
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.14.6/x64/src/testing/testing.go:1090 +0x701
FAIL	gorm.io/playground	0.082s
FAIL
```

**Comment by jinzhu** [comment]
Fixed, thank you for your report.
