### ISSUE TITLE
There is a panic when DB.WithContext(ctx).Transaction is called on a canceled context

### ISSUE THREAD

**Issue by compnski** [go-gorm/gorm#3271]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/72

## Description

I'm wrapping my db code in calls to .WithContext(ctx).Transaction(func).

I have a gRPC server receiving requests. When the server is shutdown, the context is canceled.
I expect the DB operations to fail, which they do if the cancel comes inside the transaction, but was surprised to see a panic when the cancel happened prior to the transaction.

```
2020/08/14 17:50:02 /Users/jason/src/github/playground/main_test.go:33 context canceled
[0.102ms] [rows:0] INSERT INTO `users` (`created_at`,`updated_at`,`deleted_at`,`name`,`age`,`birthday`,`company_id`,`manager_id`,`active`) VALUES ("2020-08-14 17:50:02.364","2020-08-14 17:50:02.364",NULL,"foobar",0,NULL,NULL,NULL,false)
--- FAIL: TestGORM (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x421f843]

goroutine 12 [running]:
testing.tRunner.func1.1(0x49a8060, 0x5030bd0)
	/usr/local/Cellar/go/1.14.6/libexec/src/testing/testing.go:988 +0x452
testing.tRunner.func1(0xc00064d560)
	/usr/local/Cellar/go/1.14.6/libexec/src/testing/testing.go:991 +0x600
panic(0x49a8060, 0x5030bd0)
	/usr/local/Cellar/go/1.14.6/libexec/src/runtime/panic.go:975 +0x3e3
database/sql.(*Tx).rollback(0x0, 0x400d800, 0x0, 0x0)
	/usr/local/Cellar/go/1.14.6/libexec/src/database/sql/sql.go:2114 +0x53
database/sql.(*Tx).Rollback(0x0, 0x4b483a0, 0x0)
	/usr/local/Cellar/go/1.14.6/libexec/src/database/sql/sql.go:2146 +0x3e
gorm.io/gorm.(*DB).Rollback(0xc000211d40, 0xc000485c90)
	/Users/jason/src/github/playground/gorm/finisher_api.go:459 +0xff
gorm.io/gorm.(*DB).Transaction.func2(0xc000485ccf, 0xc000485e28, 0xc000211d40)
	/Users/jason/src/github/playground/gorm/finisher_api.go:403 +0x69
gorm.io/gorm.(*DB).Transaction(0xc000211c80, 0xc00000fe40, 0x0, 0x0, 0x0, 0x4b36ec0, 0xc00006db30)
	/Users/jason/src/github/playground/gorm/finisher_api.go:415 +0x1ac
gorm.io/playground.TestGORM(0xc00064d560)
	/Users/jason/src/github/playground/main_test.go:26 +0x258
testing.tRunner(0xc00064d560, 0x4a58708)
	/usr/local/Cellar/go/1.14.6/libexec/src/testing/testing.go:1039 +0x1ec
created by testing.(*T).Run
	/usr/local/Cellar/go/1.14.6/libexec/src/testing/testing.go:1090 +0x701
FAIL	gorm.io/playground	0.776s
FAIL```

**Comment by jinzhu** [comment]
Fixed, thank you for your report.

**Comment by compnski** [comment]
Thanks for the quick fix.
