### ISSUE TITLE
gorm v2: SIGSEGV in db.Migrator() usage

### ISSUE THREAD

**Issue by Lavode** [go-gorm/gorm#3304]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/86

## Description

Trying to use `db.Migrator()` to create / drop tables causes a `SIGSEGV`:

Code in question, assuming `DB` to be a properly initialized `gorm.DB` type:
```
DB.Migrator().DropTable("documents")
```

Observed panic:
```panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6d1ad6]

goroutine 5 [running]:
testing.tRunner.func1.1(0xd50620, 0x13ae0c0)
	/usr/lib/go/src/testing/testing.go:988 +0x452
testing.tRunner.func1(0xc00018d9e0)
	/usr/lib/go/src/testing/testing.go:991 +0x600
panic(0xd50620, 0x13ae0c0)
	/usr/lib/go/src/runtime/panic.go:975 +0x3e3
gorm.io/gorm/migrator.Migrator.CreateTable.func1(0xc00044e4e0, 0x188, 0xc00027fad0)
	/home/michael/dev/go/gorm-playground/gorm/migrator/migrator.go:156 +0x166
gorm.io/gorm/migrator.Migrator.RunWithValue(0xc000236201, 0xc000236240, 0xef4f80, 0xc0001e96b0, 0xd27c20, 0xc0001e96d0, 0xc000050db0, 0xc00013f700, 0xc0001e96e0)
	/home/michael/dev/go/gorm-playground/gorm/migrator/migrator.go:44 +0x18e
gorm.io/gorm/migrator.Migrator.CreateTable(0xc00013f701, 0xc000236240, 0xef4f80, 0xc0001e96b0, 0xc0001e96c0, 0x1, 0x1, 0x424068, 0x10)
	/home/michael/dev/go/gorm-playground/gorm/migrator/migrator.go:149 +0x21e
gorm.io/playground.TestGORM(0xc00018d9e0)
	/home/michael/dev/go/gorm-playground/main_test.go:12 +0x118
testing.tRunner(0xc00018d9e0, 0xe00e50)
	/usr/lib/go/src/testing/testing.go:1039 +0x1ec
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:1090 +0x701

```

**Comment by Lavode** [comment]
Ah, I just figured out the cause of the issue - it might be a documentation one. :P 

http://v2.gorm.io/docs/migration.html allows usage of eg `DropTable()` with a string, representing the table name:
```
db.Migrator().DropTable("users")
```

However this causes the panic as per above. If one passes it a point to the model in question, it works just fine:
```
db.Migrator().DropTable(&User{})
```

**Comment by Lavode** [comment]
Apologies - as is often the case, the problem was between keyboard and chair. Turns out passing an `int` - rather than a `string` - to `DropTable()` tends to cause issues. ;)
