### ISSUE TITLE
Failed to auto migrate, but got error Error 1170: BLOB/TEXT column 'user_refer' used in key specification without a key length

### ISSUE THREAD

**Issue by diluga** [go-gorm/gorm#3369]
## Description
when i used User.Name for  primary_key,call AutoMigrate() will got error,like this:

```
2020/09/03 15:05:30 /Users/mybook/go/src/demo/src/db/connect.go:30 Error 1170: BLOB/TEXT column 'user_refer' used in key specification without a key length
[0.417ms] [rows:0] CREATE TABLE `credit_cards` (`number` longtext,`user_refer` longtext,CONSTRAINT `fk_users_credit_cards` FOREIGN KEY (`user_refer`) REFERENCES `users`(`name`))
2020/09/03 15:05:30 Failed to auto migrate, but got error Error 1170: BLOB/TEXT column 'user_refer' used in key specification without a key length

```

my models :

```
type User struct {
	Name string `gorm:"primary_key"`
	CreditCards []CreditCard `gorm:"foreignKey:UserRefer"`
}

type CreditCard struct {
	Number    string
	UserRefer string
}
```

ENV

```
gorm.io/driver/mysql v1.0.1
gorm.io/gorm v1.20.0

go version go1.14.4 darwin/amd64

```

**Comment by jinzhu** [comment]
set size for field `UserRefer`, e.g:

```go
type CreditCard struct {
	Number    string
	UserRefer string `gorm:"size:191"`
}
```

**Comment by diluga** [comment]
> set size for field `UserRefer`, e.g:
> 
> ```go
> type CreditCard struct {
> 	Number    string
> 	UserRefer string `gorm:"size:191"`
> }
> ```

thx!

**Comment by m90** [comment]
I am running into the same issue, but adding a s`size` value to my primary key definition like this:

```go
type Secret struct {
	SecretID        string `gorm:"primary_key,size:64"`
	EncryptedSecret string `gorm:"type:text"`
}
```

will make SQLite panic with a nil pointer derefence on calling `AutoMigrate`

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x73abcd]

goroutine 7 [running]:
testing.tRunner.func1.1(0x91b100, 0xe49f40)
	/usr/local/go/src/testing/testing.go:1057 +0x30d
testing.tRunner.func1(0xc0001b6780)
	/usr/local/go/src/testing/testing.go:1060 +0x41a
panic(0x91b100, 0xe49f40)
	/usr/local/go/src/runtime/panic.go:969 +0x175
gorm.io/gorm/schema.(*Schema).guessRelation(0xc000220000, 0xc0001fe360, 0xc000224000, 0x0)
	/home/frederik/projects/go/pkg/mod/gorm.io/gorm@v1.20.2/schema/relationship.go:443 +0x42d
gorm.io/gorm/schema.(*Schema).parseRelation(0xc000220000, 0xc000224000)
	/home/frederik/projects/go/pkg/mod/gorm.io/gorm@v1.20.2/schema/relationship.go:86 +0xa9a
gorm.io/gorm/schema.Parse(0x912300, 0xc000204230, 0xc0001fc360, 0xa180e0, 0xc0001e8640, 0x0, 0x0, 0x0)
	/home/frederik/projects/go/pkg/mod/gorm.io/gorm@v1.20.2/schema/schema.go:226 +0x1eeb
gorm.io/gorm.(*Statement).Parse(0xc000103520, 0x912300, 0xc000204230, 0x203000, 0x203000)
	/home/frederik/projects/go/pkg/mod/gorm.io/gorm@v1.20.2/statement.go:394 +0x76
gorm.io/gorm/migrator.Migrator.ReorderModels.func1(0x912300, 0xc000204230, 0x418d01)
	/home/frederik/projects/go/pkg/mod/gorm.io/gorm@v1.20.2/migrator/migrator.go:610 +0x151
gorm.io/gorm/migrator.Migrator.ReorderModels(0x8fc301, 0xc0001fc5a0, 0xa195e0, 0xc0001a7fb0, 0xc0001db080, 0x6, 0x6, 0x423501, 0xc0001e9680, 0xc000151da8, ...)
	/home/frederik/projects/go/pkg/mod/gorm.io/gorm@v1.20.2/migrator/migrator.go:671 +0x5fb
gorm.io/gorm/migrator.Migrator.AutoMigrate(0xc0001fc501, 0xc0001fc5a0, 0xa195e0, 0xc0001a7fb0, 0xc0001db080, 0x6, 0x6, 0x0, 0x0)
	/home/frederik/projects/go/pkg/mod/gorm.io/gorm@v1.20.2/migrator/migrator.go:84 +0x95
gorm.io/gorm.(*DB).AutoMigrate(0xc0001fc390, 0xc0001db080, 0x6, 0x6, 0x0, 0x0)
	/home/frederik/projects/go/pkg/mod/gorm.io/gorm@v1.20.2/migrator.go:17 +0x5d
github.com/offen/offen/server/persistence/relational.createTestDatabase(0x0, 0xc00003e748)
	/home/frederik/projects/offen/offen/server/persistence/relational/relational_test.go:22 +0x2bc
github.com/offen/offen/server/persistence/relational.TestRelationalDAL_CreateAccount.func2(0xc0001b6780)
	/home/frederik/projects/offen/offen/server/persistence/relational/accounts_test.go:40 +0x45
testing.tRunner(0xc0001b6780, 0xc0001a7800)
	/usr/local/go/src/testing/testing.go:1108 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1159 +0x386
```

Any idea what might be causing this?

**Comment by justincletus** [comment]
> set size for field `UserRefer`, e.g:
> 
> ```go
> type CreditCard struct {
> 	Number    string
> 	UserRefer string `gorm:"size:191"`
> }
> ```

@diluga Thanks this works for me too

**Comment by mafif21** [comment]
> ```go
> size:191
> ```

TYSM bro its work for me ✨
