### ISSUE TITLE
Find().Pluck() cause panic

### ISSUE THREAD

**Issue by seon1-kim** [go-gorm/gorm#3616]
Panic occurs when the Find() and the Pluck() are used together. 
The type below consists of the same structure as the type I use.

playground : https://github.com/go-gorm/playground/pull/181

---

model
```
type Sample struct {
	SampleId      string
	OtherSampleId string
}
```

query
```
	db = db.Debug()
	db.AutoMigrate(&Sample{})
	db.Create([]*Sample{
		{
			SampleId:      "s-1",
			OtherSampleId: "ss-1",
		},
		{
			SampleId:      "s-2",
			OtherSampleId: "ss-2",
		},
		{
			SampleId:      "s-3",
			OtherSampleId: "ss-3",
		},
	})
	var result []*Sample
	var ids []string
	if err := db.Find(&result).Pluck("other_sample_id", &ids).Error; err != nil {
		fmt.Println(err)
	}
```

log
```
2020/10/16 12:29:55 /Users/user/go/src/github.com/user/gorm2test/main.go:31
[0.080ms] [rows:-] SELECT DATABASE()

2020/10/16 12:29:55 /Users/user/go/src/github.com/user/gorm2test/main.go:31
[0.293ms] [rows:-] SELECT count(*) FROM information_schema.tables WHERE table_schema = 'testdatabase' AND table_name = 'samples' AND table_type = 'BASE TABLE'

2020/10/16 12:29:55 /Users/user/go/src/github.com/user/gorm2test/main.go:31
[0.149ms] [rows:-] SELECT * FROM `samples` LIMIT 1

2020/10/16 12:29:55 /Users/user/go/src/github.com/user/gorm2test/main.go:32
[0.685ms] [rows:3] INSERT INTO `samples` (`sample_id`,`other_sample_id`) VALUES ('s-1','ss-1'),('s-2','ss-2'),('s-3','ss-3')

2020/10/16 12:29:55 /Users/user/go/src/github.com/user/gorm2test/main.go:47
[0.147ms] [rows:1] SELECT * FROM `samples`
panic: reflect: call of reflect.Value.Field on string Value

goroutine 1 [running]:
reflect.Value.Field(0x14de860, 0xc0002ae310, 0x198, 0x0, 0xc000126960, 0x10155d3, 0xc0002ae340)
        /usr/local/go/src/reflect/value.go:837 +0x122
gorm.io/gorm/schema.(*Field).setupValuerAndSetter.func5(0x14de860, 0xc0002ae310, 0x198, 0x14de860, 0xc0002ae340, 0xc0002ae320)
        /Users/user/go/pkg/mod/gorm.io/gorm@v1.20.2/schema/field.go:429 +0x70
gorm.io/gorm/schema.(*Field).setupValuerAndSetter.func13(0x14de860, 0xc0002ae310, 0x198, 0x14de860, 0xc0002ae340, 0xc0002ae340, 0xc0003043c0)
        /Users/user/go/pkg/mod/gorm.io/gorm@v1.20.2/schema/field.go:692 +0x5fe
gorm.io/gorm/schema.(*Field).setupValuerAndSetter.func8(0x14de860, 0xc0002ae310, 0x198, 0x14d1e60, 0xc0002ae320, 0xc0002be120, 0x149e7ab, 0x7)
        /Users/user/go/pkg/mod/gorm.io/gorm@v1.20.2/schema/field.go:499 +0x258
gorm.io/gorm/schema.(*Field).setupValuerAndSetter.func13(0x14de860, 0xc0002ae310, 0x198, 0x14d1e60, 0xc0002ae320, 0xc0002ae320, 0xc000306c30)
        /Users/user/go/pkg/mod/gorm.io/gorm@v1.20.2/schema/field.go:700 +0x34d
gorm.io/gorm/schema.(*Field).setupValuerAndSetter.func8(0x14de860, 0xc0002ae310, 0x198, 0xc00030a200, 0xc0002ac050, 0xc0002be120, 0x2, 0x0)
        /Users/user/go/pkg/mod/gorm.io/gorm@v1.20.2/schema/field.go:499 +0x258
gorm.io/gorm/schema.(*Field).setupValuerAndSetter.func13(0x14de860, 0xc0002ae310, 0x198, 0xc00030a200, 0xc0002ac050, 0x0, 0x97)
        /Users/user/go/pkg/mod/gorm.io/gorm@v1.20.2/schema/field.go:700 +0x34d
gorm.io/gorm.Scan(0xc000302480, 0xc0002aa480, 0xc000016000)
        /Users/user/go/pkg/mod/gorm.io/gorm@v1.20.2/scan.go:178 +0x94a
gorm.io/gorm/callbacks.Query(0xc0002aa480)
        /Users/user/go/pkg/mod/gorm.io/gorm@v1.20.2/callbacks/query.go:34 +0x1e8
gorm.io/gorm.(*processor).Execute(0xc000071dc0, 0xc0002aa480)
        /Users/user/go/pkg/mod/gorm.io/gorm@v1.20.2/callbacks.go:101 +0x224
gorm.io/gorm.(*DB).Pluck(0xc0002aa480, 0xc00029a0d0, 0xf, 0x14c72e0, 0xc0003041c0, 0x0)
        /Users/user/go/pkg/mod/gorm.io/gorm@v1.20.2/finisher_api.go:397 +0x1f9
main.main()
        /Users/user/go/src/github.com/user/gorm2test/main.go:47 +0x4cf
exit status 2
```

**Comment by jinzhu** [comment]
https://gorm.io/docs/method_chaining.html

**Comment by amanhigh** [comment]
I am also facing this issue and it does not seem to be getting solved by Method Chain Goroutine.

@seon1-kim Were you able to make it work ?
