### ISSUE TITLE
panic:concurrent map writes

### ISSUE THREAD

**Issue by SnowfallDan** [go-gorm/gorm#3643]
I find this issue when i test the gorm benchmark.

I write a test program to test the concurrent instead of go-test.

test program is below:
```go
package main

import (
	"flag"
	"fmt"
	"gorm.io/driver/mysql"
	_ "gorm.io/driver/mysql"
	"gorm.io/gorm"
	_ "gorm.io/gorm"
	"gorm.io/gorm/logger"
	"gorm.io/plugin/dbresolver"
	"log"
	"os"
	"sync"
	"time"
)

//定义数据库（集群）链接
type ConnsInfo struct {
	UserName      string
	Password      string
	Hosts         []string
	DBName        string
	slowThreshold int32
}

var conns = ConnsInfo{
	UserName: "root",
	Password: "xxxxx",
	Hosts:    []string{"10.242.96.2:4000", "10.242.96.3:4000", "10.242.96.4:4000"},
	DBName:   "iceberg2",
}

func initLogger(slowThreshold int32) logger.Interface {
	newLogger := logger.New(
		log.New(os.Stdout, "\r\n", log.LstdFlags),
		logger.Config{
			SlowThreshold: time.Duration(slowThreshold) * time.Second, // 慢 SQL 阈值
			LogLevel:      logger.Error,                               // Log level
			Colorful:      false,                                      // 禁用彩色打印
		},
	)

	return newLogger
}

var Tidb *gorm.DB = nil

// 初始化数据库链接配置
func GeneratorDsn(MyUser, Password, Host, DataBase string) (dsn string) {
	// mysql Dsn示例 "root:root@tcp(localhost:4000)/tests?charset=utf8&parseTime=true"
	dsn = fmt.Sprintf("%s:%s@tcp(%s)/%s?charset=utf8&parseTime=true", MyUser, Password, Host, DataBase)
	return
}

// 初始化数据库集群链接配置
func GeneratorClusterDsn(MyUser string, Password string, Hosts []string, DataBase string) (dialectors []gorm.Dialector) {
	for _, host := range Hosts {
		dialectors = append(dialectors, mysql.Open(GeneratorDsn(MyUser, Password, host, DataBase)))
	}

	return
}

func InitClusterDbConn(conn ConnsInfo) (err error) {
	DB, err := gorm.Open(mysql.New(mysql.Config{
		DSN: GeneratorDsn(conn.UserName, conn.Password, conn.Hosts[0], conn.DBName),
	}), &gorm.Config{
		SkipDefaultTransaction: true,
		PrepareStmt:            true,
		Logger:                 initLogger(conn.slowThreshold),
	})

	if err != nil {
		return err
	}

	if len(conn.Hosts) > 1 {
		err = DB.Use(dbresolver.Register(dbresolver.Config{
			Sources: GeneratorClusterDsn(conn.UserName, conn.Password, conn.Hosts, conn.DBName),
			// load balancing policy
			Policy: dbresolver.RandomPolicy{},
		}))
	}

	Tidb = DB

	if sqlDB, err := DB.DB(); err != nil {
		return err
	} else {
		sqlDB.SetConnMaxIdleTime(time.Hour)
		sqlDB.SetConnMaxLifetime(24 * time.Hour)
		sqlDB.SetMaxIdleConns(50)
		sqlDB.SetMaxOpenConns(100)

		return sqlDB.Ping()
	}
}

func main() {
	var gonum int
	var host string
	var err error
	loop := 100

	flag.IntVar(&gonum, "n", 1100, "100")
	flag.StringVar(&host, "h", "127.0.0.1:8888", "ip:port")
	flag.Parse()
	fmt.Printf("gonum=%d loop=%d\n", gonum, loop)

	if err = InitClusterDbConn(conns); err != nil {
		//if err = orm.InitDbConn(conns); err != nil {
		panic("InitDb error")
	}
	wg := sync.WaitGroup{}
	wg.Add(gonum)

	startTime := time.Now().UnixNano()

	for k := 0; k < gonum; k++ {
		go func(j int) {
			for i := 0; i < loop; i++ {
				_ = testInsert(j*loop + i)
				if i%loop == 0 {
					fmt.Printf("------i=%d----\n", i)
				}
			}
			wg.Done()
		}(k)
	}

	wg.Wait()

	endTime := time.Now().UnixNano()

	uSeconds := uint64(endTime-startTime) / 1000
	fmt.Printf("mSec=%v N/s=%v\n", uSeconds/1000, uint64(gonum)*1000*1000*uint64(loop)/uSeconds)
}

type Model struct {
	Id      int    `gorm:"id;AUTO_INCREMENT;primary_key" column:"id"`
	Name    string `gorm:"name" column:"name"`
	Title   string `gorm:"title" column:"title"`
	Fax     string `column:"fax"`
	Web     string `column:"web"`
	Age     int    `column:"age"`
	Counter int64  `column:"counter"`
}

func NewModel() *Model {
	m := new(Model)
	m.Name = "Orm Benchmark"
	m.Title = "Just a Benchmark for fun"
	m.Fax = "99909990"
	m.Web = "http://beego.me"
	m.Age = 100
	m.Counter = 1000
	return m
}

func testInsert(i int) error {
	if err := Tidb.Create(NewModel()).Error; err != nil {
		fmt.Printf("insert err=%s\n", err.Error())
	}
	return nil
}

```

I create 1100 goroutines and test the insert on 100 conns to DB.

The program may panic at this point below Not every time:
![image](https://user-images.githubusercontent.com/16498700/96686411-1527c880-13b1-11eb-9307-99c0dd01502f.png)

**Comment by jinzhu** [comment]
HI @SnowfallDan 

Can you confirm this issue has been fixed with latest version?

**Comment by MIcQo** [comment]
I Have same problem. v1.20.5

**Comment by zzzhr1990** [comment]
Same problem, fatal error: concurrent map writes, v1.20.7

```golang
goroutine 109 [running]:
runtime.throw(0xc9095f, 0x15)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc0003235e0 sp=0xc0003235b0 pc=0x4377f2
runtime.mapassign_faststr(0xb95c00, 0xc0007242a0, 0xc83b7c, 0x5, 0xc000139908)
	/usr/local/go/src/runtime/map_faststr.go:211 +0x3f1 fp=0xc000323648 sp=0xc0003235e0 pc=0x415e71
gorm.io/gorm.(*Statement).AddClause(0xc0000ac1a0, 0xd5ce60, 0xc0002fae50)
	/go/pkg/mod/gorm.io/gorm@v1.20.7/statement.go:230 +0x19c fp=0xc0003236a0 sp=0xc000323648 pc=0x98477c
gorm.io/gorm.(*DB).Limit(0xc000724270, 0x1, 0x8)
	/go/pkg/mod/gorm.io/gorm@v1.20.7/chainable_api.go:223 +0x90 fp=0xc0003236f0 sp=0xc0003236a0 pc=0x974f10
gorm.io/gorm.(*DB).First(0xc000724270, 0xb3a440, 0xc0004c69c0, 0xc00023a720, 0x2, 0x2, 0x26)
	/go/pkg/mod/gorm.io/gorm@v1.20.7/finisher_api.go:92 +0x49 fp=0xc000323790 sp=0xc0003236f0 pc=0x976169
gitlab.com/qingzhenyun/go-user-center/service.(*UserService).FindOne(0xc0003f0280, 0x690f, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd68ba0, 0xc0004c5770, ...)
	/src/service/repo_user.go:164 +0x585 fp=0xc000323840 sp=0xc000323790 pc=0xad0e45
```
