### ISSUE TITLE
Reusable queries are not supported

### ISSUE THREAD

**Issue by loeffel-io** [go-gorm/gorm#3713]
Hey @jinzhu 

with the v1 of gorm we just reused "queries" like this: 

```go 
func (database *Database) CompanyUsers(connection *gorm.DB, companyUsers []*model.CompanyUser, company *model.Company, pagination *paginator.Paginator, filters []database_filter.Filter) ([]*model.CompanyUser, error) {
	var g errgroup.Group
	var query = connection.
		Where("company_users.company_id = ?", company.GetId())

	for _, filter := range filters {
		query = filter.GetQuery(query)
	}

	g.Go(func() error {
		return query.
			Preload("Role").
			Preload("User").
			Offset(pagination.Offset()).
			Limit(pagination.GetLimit()).
			Find(&companyUsers).
			Error
	})

	g.Go(func() error {
		return query.
			Select("COUNT(company_users.id) as total").
			Table("company_users").
			Where("company_users.deleted_at IS NULL").
			Scan(pagination).
			Error
	})

	if err := g.Wait(); err != nil {
		return nil, err
	}

	return companyUsers, nil
}
```

With todays update to gorm v2 this is not longer possible: 

```go
panic: reflect: Field index out of range

goroutine 53 [running]:
reflect.Value.Field(0xe4ff40, 0xc0005edde0, 0x199, 0x5, 0x40e298, 0x30, 0xe4fa40)
        /usr/local/Cellar/go/1.15/libexec/src/reflect/value.go:853 +0xd9
gorm.io/gorm/schema.(*Field).setupValuerAndSetter.func1(0xe4ff40, 0xc0005edde0, 0x199, 0xc0004b5310, 0x8, 0x1)
        /Users/lucasloffel/go/pkg/mod/gorm.io/gorm@v1.20.5/schema/field.go:388 +0x85
gorm.io/gorm/schema.GetIdentityFieldValuesMap(0xe4ff40, 0xc0005edde0, 0x199, 0xc000014278, 0x1, 0x1, 0x0, 0x1, 0x1, 0x1)
        /Users/lucasloffel/go/pkg/mod/gorm.io/gorm@v1.20.5/schema/utils.go:113 +0x8fc
gorm.io/gorm/callbacks.preload(0xc0005827e0, 0xc000014268, 0x1, 0x1, 0x0, 0x0, 0x0)
        /Users/lucasloffel/go/pkg/mod/gorm.io/gorm@v1.20.5/callbacks/preload.go:89 +0x2e85
gorm.io/gorm/callbacks.Preload(0xc0005827e0)
        /Users/lucasloffel/go/pkg/mod/gorm.io/gorm@v1.20.5/callbacks/query.go:209 +0x685
gorm.io/gorm.(*processor).Execute(0xc0000a40c0, 0xc0005827e0)
        /Users/lucasloffel/go/pkg/mod/gorm.io/gorm@v1.20.5/callbacks.go:105 +0x23d
gorm.io/gorm.(*DB).Find(0xc0005827e0, 0xe1f340, 0xc0005edde0, 0x0, 0x0, 0x0, 0xc0005827e0)
        /Users/lucasloffel/go/pkg/mod/gorm.io/gorm@v1.20.5/finisher_api.go:113 +0xba
github.com/finsmart-gmbh/api/database.(*Database).CompanyUsers.func2(0xc00004afc0, 0x7bd205)
        /Users/lucasloffel/go/src/github.com/finsmart-gmbh/api/database/company.go:123 +0x105
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0005827b0, 0xc0005ede80)
        /Users/lucasloffel/go/pkg/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
        /Users/lucasloffel/go/pkg/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:54 +0x66
```

Is there any reason for this? maybe i missed something from the migration guide 

Have a good day, thanks!

**Comment by jinzhu** [comment]
https://gorm.io/docs/v2_release_note.html#Method-Chain-Safety-Goroutine-Safety

**Comment by loeffel-io** [comment]
Thanks!

**Comment by loeffel-io** [comment]
One more question: 

Added a session for both queries

```go 
func (database *Database) CompanyUsers(connection *gorm.DB, companyUsers []*model.CompanyUser, company *model.Company, pagination *paginator.Paginator, filters []database_filter.Filter) ([]*model.CompanyUser, error) {
	var g errgroup.Group
	var query = connection.
		Where("company_users.company_id = ?", company.GetId())

	for _, filter := range filters {
		query = filter.GetQuery(query)
	}

	g.Go(func() error {
		return query.
			Session(&gorm.Session{WithConditions: true}).
			Preload("Role").
			Preload("User").
			Offset(pagination.Offset()).
			Limit(pagination.GetLimit()).
			Find(&companyUsers).
			Error
	})

	g.Go(func() error {
		return query.
			Session(&gorm.Session{WithConditions: true}).
			Select("COUNT(company_users.id) as total").
			Table("company_users").
			Where("company_users.deleted_at IS NULL").
			Scan(pagination).
			Error
	})

	if err := g.Wait(); err != nil {
		return nil, err
	}

	return companyUsers, nil
}
```

and call the companyUsers method with the context 

```go 
CompanyUsers(http.GetDatabase().GetConnection().WithContext(c), ...
```

my question: is the context still attached to both `New Session Methods`? 

For example: if i cancel the context, will be both `New Session Methods` cancelled? 

Thanks!
