### ISSUE TITLE
Batch insert does not work

### ISSUE THREAD

**Issue by wenhsinhsieh** [go-gorm/gorm#3714]
## Your Question

I follow the document about batch insert, but I can't get it to work. I get the following error message:
```
panic: reflect: call of reflect.Value.Interface on zero Value [recovered]
        panic: reflect: call of reflect.Value.Interface on zero Value

goroutine 1 [running]:
github.com/jinzhu/gorm.(*Scope).callCallbacks.func1(0xc0001c8400)
        C:/Users/wenh/go/pkg/mod/github.com/jinzhu/gorm@v1.9.16/scope.go:865 +0xb7
panic(0x712d60, 0xc000226860)
        C:/Go/src/runtime/panic.go:969 +0x174
reflect.valueInterface(0x0, 0x0, 0x0, 0x1, 0x1, 0xc0001d2b40)
        C:/Go/src/reflect/value.go:1005 +0x1ac
reflect.Value.Interface(...)
        C:/Go/src/reflect/value.go:1000
github.com/jinzhu/gorm.createCallback(0xc0001c8400)
        C:/Users/wenh/go/pkg/mod/github.com/jinzhu/gorm@v1.9.16/callback_create.go:68 +0x7ca
github.com/jinzhu/gorm.(*Scope).callCallbacks(0xc0001c8400, 0xc0001c1d80, 0x9, 0x10, 0x0)
        C:/Users/wenh/go/pkg/mod/github.com/jinzhu/gorm@v1.9.16/scope.go:869 +0x8a
github.com/jinzhu/gorm.(*DB).Create(0xc0001bda00, 0x6ef120, 0xc000226760, 0x1)
        C:/Users/wenh/go/pkg/mod/github.com/jinzhu/gorm@v1.9.16/main.go:483 +0x86
main.main()
        C:/Users/wenh/go/src/testgorm/main.go:18 +0x1af
exit status 2
```

And here is my code:

```
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/postgres"
)

type User struct {
	ID   int
	Name string
}

func main() {
	db, _ := gorm.Open("postgres", "host=192.168.1.101 port=5432 user=dbuser dbname=db password=1234")
	db.AutoMigrate(&User{})
	defer db.Close()
	var users = []User{{Name: "jinzhu1"}, {Name: "jinzhu2"}, {Name: "jinzhu3"}}
	db.Create(&users)
}
```

## The document you expected this should be explained

https://gorm.io/docs/create.html#Batch-Insert

## Expected answer

The working example

**Comment by jinzhu** [comment]
GORM v2
