### ISSUE TITLE
Concurrent FindOne()

### ISSUE THREAD

**Issue by zzzhr1990** [go-gorm/gorm#3799]
## Your Question

I write a test program test concurrent query, but got this exception:

```golang
	ix := 0
	ch := make(chan bool)
	name := "testname"
	connectString := "...."
	testDb, err := gorm.Open(mysql.Open(connectString), &gorm.Config{})

	if err != nil {
		log.Errorf("test db cannot connect: %v", err)
	}
	userTable := testDb.Table("v3_user_info")
	for ix < 200 {
		go func() {
			// concurrent
			resp := &model.User{}
			err := userTable.First(resp, "name = ?", name).Error

			log.Infof("test find: %v -> error: %v", resp.Name, err)
		}()
		ix++
	}
	<-ch
```

the exception i got:

```golang
fatal error: concurrent map writes

goroutine 72 [running]:
runtime.throw(0xc89c9f, 0x15)
	/usr/local/Cellar/go/1.15.4/libexec/src/runtime/panic.go:1116 +0x72 fp=0xc00062cd90 sp=0xc00062cd60 pc=0x435d32
runtime.mapassign_faststr(0xb8f4a0, 0xc0002eec30, 0xc7cedc, 0x5, 0xc000315908)
	/usr/local/Cellar/go/1.15.4/libexec/src/runtime/map_faststr.go:211 +0x3f1 fp=0xc00062cdf8 sp=0xc00062cd90 pc=0x4143b1
gorm.io/gorm.(*Statement).AddClause(0xc0003681a0, 0xd55880, 0xc00011e080)
	/Users/zzzhr/go/pkg/mod/gorm.io/gorm@v1.20.7/statement.go:230 +0x19c fp=0xc00062ce50 sp=0xc00062cdf8 pc=0x96e09c
gorm.io/gorm.(*DB).Limit(0xc0002eec00, 0x1, 0x10)
	/Users/zzzhr/go/pkg/mod/gorm.io/gorm@v1.20.7/chainable_api.go:223 +0x90 fp=0xc00062cea0 sp=0xc00062ce50 pc=0x95e830
gorm.io/gorm.(*DB).First(0xc0002eec00, 0xb341c0, 0xc000624000, 0xc00010c060, 0x2, 0x2, 0x4)
	/Users/zzzhr/go/pkg/mod/gorm.io/gorm@v1.20.7/finisher_api.go:92 +0x49 fp=0xc00062cf40 sp=0xc00062cea0 pc=0x95fa89
main.main.func2(0xc0002eec00, 0xc80d9e, 0x8)
	/Users/zzzhr/vscode/go/go-user-center/server.go:100 +0xec fp=0xc00062cfc8 sp=0xc00062cf40 pc=0xaee56c
runtime.goexit()
	/usr/local/Cellar/go/1.15.4/libexec/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00062cfd0 sp=0xc00062cfc8 pc=0x46abc1
created by main.main
	/Users/zzzhr/vscode/go/go-user-center/server.go:97 +0x46a

goroutine 1 [chan receive]:
main.main()
	/Users/zzzhr/vscode/go/go-user-center/server.go:106 +0x4a5
```

**Comment by jinzhu** [comment]
https://gorm.io/docs/method_chaining.html#Method-Chain-Safety-Goroutine-Safety
