### ISSUE TITLE
Model creation breaks

### ISSUE THREAD

**Issue by kitt3911** [go-gorm/gorm#4118]
## hi, i'm not quite a database specialist, so sorry for the possibly stupid problem, but i'm writing a telegram bot to track costs, and there are the following models : 

**category.go**
```go
type Category struct {
	gorm.Model
	UserID       int    `gorm:"primaryKey"`
	Name         string `json:"name"`
	TotalCost    int    `json:"total_cost"`
	RelatedGoods []Good `json:"related_goods" gorm:"foreignKey:UserID"`
}

type Good struct {
	gorm.Model
	UserID int    `gorm:"primaryKey"`
	Name   string `json:"name_related_goods"`
}

```
**moneyBox.go**
```go
type MoneyBox struct {
	gorm.Model
	UserID         int        `json:"user_id" gorm:"primaryKey"`
	MonthlyAmount  int        `json:"monthly_amount"`
	Balance        int        `json:"balance"`
	TotalCost      int        `json:"total_cost"`
	MonthlyСosts   int        `json:"monthly_costs"`
	Caretaking     int        `json:"caretaking"`
	Payday         int        `json:"payday"`
	CostByCategory []Category `json:"cost_by_category" gorm:"foreignKey:UserID"`
}

```

Connections :

**database.go**

```go
var (
	Database *gorm.DB
)

/*Init()
initial connect to database and read config from .env*/
func Init(config *config.Config) (*gorm.DB, error) {
	dbConnect := fmt.Sprintf("host=%s port=%d user=%s "+
		"password=%s dbname=%s",
		"localhost", 5432, config.DB.User, config.DB.Password, config.DB.Name)

	Database, err := gorm.Open(postgres.Open(dbConnect), &gorm.Config{})
	

	Database.Table("RelatedGoods").AutoMigrate(&model.Good{})
	Database.Table("Categories").AutoMigrate(&model.Category{})
	Database.Table("MoneyBoxes").AutoMigrate(&model.MoneyBox{})

	Database.Model(&model.MoneyBox{}).Association("Categories")
	Database.Model(&model.Category{}).Association("RelatedGoods")

	if err != nil {
		return Database, err
	}

	return Database, nil
}

```
The program breaks at the moment of start here:

**addService.go**
```go
func InitMoneyBox(userId int) {
	database.Database.Create(&model.MoneyBox{
		UserID: userId,
		MonthlyAmount: 0,
		MonthlyСosts: 0,
		Balance: 0,
		TotalCost: 0,
		Caretaking: 0,
		Payday: 0,
	})
}
```

```fish
Service has been started!
2021/02/23 23:46:52 getUpdates resp: {"ok":true,"result":[{"update_id":146403282,
"message":{"message_id":114,"from":{"id":731839001,"is_bot":false,"first_name":"\u0418\u0432\u0430\u043d","last_name":"\u0418\u0433\u043d\u0430\u0442\u0435\u043d\u043a\u043e","username":"kitt3911","language_code":"ru"},"chat":{"id":731839001,"first_name":"\u0418\u0432\u0430\u043d","last_name":"\u0418\u0433\u043d\u0430\u0442\u0435\u043d\u043a\u043e","username":"kitt3911","type":"private"},"date":1614102412,"text":"/start","entities":[{"offset":0,"length":6,"type":"bot_command"}]}}]}
2021/02/23 23:46:52 getUpdates req : map[timeout:[60]]
2021/02/23 23:46:52 getUpdates resp: [{UpdateID:146403282 Message:0xc0001ce140 EditedMessage:<nil> ChannelPost:<nil> EditedChannelPost:<nil> InlineQuery:<nil> ChosenInlineResult:<nil> CallbackQuery:<nil> ShippingQuery:<nil> PreCheckoutQuery:<nil>}]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x771196]

goroutine 1 [running]:
gorm.io/gorm.(*DB).Create(0x0, 0x946260, 0xc00012fce0, 0x1)
        /home/kitt3911/go/pkg/mod/gorm.io/gorm@v1.20.12/finisher_api.go:18 +0x26
github.com/kitt3911/expense-managment-bot/service.InitMoneyBox(...)
        /home/kitt3911/projects/cost-according-bot/service/addService.go:13
main.main()
        /home/kitt3911/projects/cost-according-bot/main.go:66 +0x64d
exit status 2
```

## The document you expected this should be explained

help or pr
or explain it please here

repo : https://github.com/kitt3911/expense-managment-bot

## Expected answer
Explanation by code

once again sorry i'm new to this

**Comment by Xieyuschen** [comment]
# Summary
You have failed to initialize your `Database` variable successfully, it's a disaster when not handle a potential not-nil error.
# Detail  
The error message is a silent helper for you, look at here:
```
goroutine 1 [running]:
gorm.io/gorm.(*DB).Create(0x0, 0x946260, 0xc00012fce0, 0x1)
        /home/kitt3911/go/pkg/mod/gorm.io/gorm@v1.20.12/finisher_api.go:18 +0x26
github.com/kitt3911/expense-managment-bot/service.InitMoneyBox(...)
        /home/kitt3911/projects/cost-according-bot/service/addService.go:13
main.main()
        /home/kitt3911/projects/cost-according-bot/main.go:66 +0x64d
```
It shows the error stack, cause a panic and then panic from the bottom to top until stop your main goroutine(defualt routine).
- /home/kitt3911/go/pkg/mod/gorm.io/gorm@v1.20.12/finisher_api.go  
It's clear the gorm library, we don't focus it usually.  
- /home/kitt3911/projects/cost-according-bot/service/addService.go:13
It's a self written code, so error may come from here. The first line is the `addService.go:13`
```go
	database.Database.Create(&model.MoneyBox{
		UserID: userId,
		MonthlyAmount: 0,
		MonthlyСosts: 0,
		Balance: 0,
		TotalCost: 0,
		Caretaking: 0,
		Payday: 0,
	})
```
The error message also told me `panic: runtime error: invalid memory address or nil pointer dereference`, so it may caused by 
variable `Database` is nil which should be panic after init it. To confirm it, look into how do you initialize your `Database`.
At [line17: database.Init(config)](https://github.com/kitt3911/expense-managment-bot/blob/fdfaf7a3f11ca1d74efb6c8c064c535e32ba7d41/main.go#L37), you Init your `Database` but not handle an error. 
So check whether your `Database` is initialized successfully, if not then handle the error and panic your program to let you know at the beginning when encounter the error.
