### ISSUE TITLE
GORM Hooks BeforeSave and BeforeUpdate causing issues while calling Updates function for updating a table entry

### ISSUE THREAD

**Issue by KBA07** [go-gorm/gorm#4332]
Consider the following GORM Struct
```
type FQDN struct {
	ID             int    `gorm:"primaryKey"`
	Name           string `gorm:"size:50;unique;not null"`
	ReverseResolve bool   `gorm:"column:rev_resolve"`
}

func (fqdn *FQDN) BeforeSave(tx *gorm.DB) (err error) {
	if !strings.Contains(fqdn.Name, ".com") {
		message := "Doesn't Contain .com"
		log.Println(message)
		return fmt.Errorf(message)
	}
	return nil
}
```

When I try to create an entry to the table using this model 

```
log.Println("Inserting a record into table FQDN")
db.Create(&FQDN{Name: "google.in", ReverseResolve: true})

db.Create(&FQDN{Name: "google.com", ReverseResolve: true})
```
I get an error for the first one - **Which is expected** and the second one is inserted properly.

```
2021/04/29 14:19:22 Inserting a record into table FQDN
2021/04/29 14:19:22 Doesn't Contain .com

2021/04/29 14:19:22 /Users/kashif.ali/go/src/github.com/SophosNSG/paloma/orm/gorm1.go:86 Doesn't Contain .com
[1.668ms] [rows:0]

postgres=# select * from fqdn_gorm;
id | name | rev_resolve
----+------------+-------------
1 | google.com | t
(1 row)
```

Now, when I try to update the already inserted entry
```
log.Println("Updating a record into table FQDN")
db.Model(FQDN{}).Where("id = ?", 1).Updates(&FQDN{Name: "facebook.com", ReverseResolve: false})
```
I get an unexpected error 
```
2021/04/29 14:51:24 Updating a record into table FQDN
panic: reflect.Value.Addr of unaddressable value

goroutine 1 [running]:
reflect.Value.Addr(0x150df00, 0xc00021d160, 0x99, 0x11ce400, 0x150df00, 0xc00021d160)
        /usr/local/go/src/reflect/value.go:258 +0x96
gorm.io/gorm/callbacks.callMethod(0xc00020daa0, 0xc000147cf8)
        /Users/kashif.ali/go/pkg/mod/gorm.io/gorm@v1.21.7/callbacks/callmethod.go:20 +0x280
gorm.io/gorm/callbacks.BeforeUpdate(0xc00020daa0)
        /Users/kashif.ali/go/pkg/mod/gorm.io/gorm@v1.21.7/callbacks/update.go:33 +0x81
gorm.io/gorm.(*processor).Execute(0xc00007dcc0, 0xc00020daa0)
        /Users/kashif.ali/go/pkg/mod/gorm.io/gorm@v1.21.7/callbacks.go:124 +0x3a1
gorm.io/gorm.(*DB).Updates(0xc00020daa0, 0x14d7020, 0xc00021d1c0, 0xc00024a2d0)
        /Users/kashif.ali/go/pkg/mod/gorm.io/gorm@v1.21.7/finisher_api.go:345 +0xa7
main.Gorm1()
        /Users/kashif.ali/go/src/github.com/KBA07/orm/gorm1.go:105 +0x537
main.main()
        /Users/kashif.ali/go/src/github.com/KBA07/orm/main.go:11 +0x7a
```

Now, When I tried changing the hooks to 

```
type FQDN struct {
	ID             int    `gorm:"primaryKey"`
	Name           string `gorm:"size:50;unique;not null"`
	ReverseResolve bool   `gorm:"column:rev_resolve"`
}

func (fqdn *FQDN) BeforeCreate(tx *gorm.DB) (err error) {
	if !strings.Contains(fqdn.Name, ".com") {
		message := "Doesn't Contain .com"
		log.Println(message)
		return fmt.Errorf(message)
	}
	return nil
}

func (fqdn *FQDN) BeforeUpdate(tx *gorm.DB) (err error) {
	if fqdn.ID > 0 {
		log.Println("Record exists updating")
	}
	return nil
}
```
Am i missing something here, or is this a bug ?

**Comment by s-takehana** [comment]
Please try
```go
db.Debug().Model(&FQDN{ID: 1}).Updates(FQDN{Name: "facebook.com", ReverseResolve: false})
```
https://gorm.io/docs/update.html#Updates-multiple-columns

**Comment by KBA07** [comment]
@s-takehana Thanks, I found the solution yesterday but forgot to close this.

Looks like the Hooks use the first argument db.Model(**&FQDN{ID: 1}**) for Update and Delete. Hence, If we have registered hook for update and delete then, one should pass the model object with those parameters which the hooks are expecting.
