### ISSUE TITLE
AutoMigrate() with PrepareStmt on a nonexistent SQLite DB inside a non-writeable directory causes a panic

### ISSUE THREAD

**Issue by ernestask** [go-gorm/gorm#4551]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/362

## Description

Using the SQLite driver, opening (with a config with `PrepareStmt` enabled) a nonexistent database inside a directory without write permissions and calling `AutoMigrate()` will cause a panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4122b76]

goroutine 1 [running]:
database/sql.(*Rows).close(0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.16.5/libexec/src/database/sql/sql.go:3165 +0x76
database/sql.(*Rows).Close(0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.16.5/libexec/src/database/sql/sql.go:3161 +0x33
panic(0x432a840, 0x44bf8b0)
	/usr/local/Cellar/go/1.16.5/libexec/src/runtime/panic.go:965 +0x1b9
database/sql.(*Rows).Next(0x0, 0xc00015dd40)
	/usr/local/Cellar/go/1.16.5/libexec/src/database/sql/sql.go:2842 +0x30
database/sql.(*Row).Scan(0xc0000a8ba0, 0xc0000d9c10, 0x1, 0x1, 0x0, 0x0)
	/usr/local/Cellar/go/1.16.5/libexec/src/database/sql/sql.go:3231 +0xf6
gorm.io/driver/sqlite.Migrator.HasTable.func1(0xc000196700, 0x4312b40, 0x44f90f0)
	/Users/T1996/go/pkg/mod/gorm.io/driver/sqlite@v1.1.4/migrator.go:32 +0x105
gorm.io/gorm/migrator.Migrator.RunWithValue(0x431a801, 0xc00015dce0, 0x43a92f0, 0xc00015dd10, 0x4312b40, 0x44f90f0, 0xc0000d9cd0, 0xc0000d9d48, 0x4174422)
	/Users/T1996/go/pkg/mod/gorm.io/gorm@v1.21.12/migrator/migrator.go:49 +0xd6
gorm.io/driver/sqlite.Migrator.HasTable(0x1, 0xc00015dce0, 0x43a92f0, 0xc00015dd10, 0x4312b40, 0x44f90f0, 0x0)
	/Users/T1996/go/pkg/mod/gorm.io/driver/sqlite@v1.1.4/migrator.go:31 +0xe5
gorm.io/gorm/migrator.Migrator.AutoMigrate(0x40da801, 0xc00015da70, 0x43a92f0, 0xc00015daa0, 0xc0001690a0, 0x1, 0x1, 0x0, 0x0)
	/Users/T1996/go/pkg/mod/gorm.io/gorm@v1.21.12/migrator/migrator.go:91 +0x16d
gorm.io/gorm.(*DB).AutoMigrate(0xc00015d860, 0xc0001690a0, 0x1, 0x1, 0x1, 0x6)
	/Users/T1996/go/pkg/mod/gorm.io/gorm@v1.21.12/migrator.go:26 +0x5d
main.main()
	/tmp/test/foo.go:15 +0x188
exit status 2
```

**Comment by ernestask** [comment]
My basic reproducer:

```
package main

import (
        "fmt"

        "gorm.io/driver/sqlite"
        "gorm.io/gorm"
)

type Foo struct{}

func main() {
        db, err := gorm.Open(sqlite.Open("nope/data.db"), &gorm.Config{PrepareStmt: true})
        fmt.Println(err)
        db.AutoMigrate(&Foo{})
}
```

**Comment by bsrinivas8687** [comment]
Hi @jinzhu @ernestask 

Anyway how to fix it without setting PrepareStmt to false?

**Comment by jinzhu** [comment]
seems no panic happen on the latest version
