### ISSUE TITLE
DropColumn String failed

### ISSUE THREAD

**Issue by ThinhNV991** [go-gorm/gorm#5805]
## GORM Playground Link

Migrations:
```
Rollback: func(tx *gorm.DB) error {
	if err := tx.Migrator().DropColumn("statistic_items", "parent_id"); err != nil {
		return err
	}
	return tx.Migrator().DropColumn("statistic_items", "embed_link")
},
```

Error
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8b75d6]

goroutine 1 [running]:
gorm.io/gorm/migrator.Migrator.DropColumn.func1(0xc00024e000, 0xc00024e000, 0xc0001114f8)
	/root/go/pkg/mod/gorm.io/gorm@v1.20.0/migrator/migrator.go:287 +0x46
gorm.io/gorm/migrator.Migrator.RunWithValue(0x7c00000000000000, 0xc0001eaf30, 0xb08d80, 0xc0001b8780, 0x95ff60, 0xaecd40, 0xc000111508, 0xc000111550, 0xc000111540)
	/root/go/pkg/mod/gorm.io/gorm@v1.20.0/migrator/migrator.go:44 +0xb3
gorm.io/gorm/migrator.Migrator.DropColumn(0x8f8800, 0xc0001eaf30, 0xb08d80, 0xc0001b8780, 0x95ff60, 0xaecd40, 0xa2b122, 0x9, 0xc0001b8780, 0xc0001b8780)
	/root/go/pkg/mod/gorm.io/gorm@v1.20.0/migrator/migrator.go:286 +0xba
main.m202011060001.func2(0xc0001eaf30, 0xc0001fb020, 0xc0001fb010)

```

[stmt.Schema.LookUpField(name)](https://github.com/go-gorm/gorm/blob/9d82aa56734999bb28e0c4d60fba69ae7cde66d5/migrator/migrator.go#L341) stmt.Schema is nil

**Comment by a631807682** [comment]
duplicated of https://github.com/go-gorm/gorm/issues/5795
